"""empty message

Revision ID: 1279f9ee540b
Revises: acc4546ded25
Create Date: 2021-06-21 14:32:42.680849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1279f9ee540b'
down_revision = 'acc4546ded25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parent_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parents_id', sa.Integer(), nullable=True),
    sa.Column('grand_parents_id', sa.Integer(), nullable=True),
    sa.Column('current_generation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_generation_id'], ['current_generation.id'], ),
    sa.ForeignKeyConstraint(['grand_parents_id'], ['grandparents.id'], ),
    sa.ForeignKeyConstraint(['parents_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('name', table_name='current__generation')
    op.drop_index('name_2', table_name='current__generation')
    op.drop_table('current__generation')
    op.add_column('grandparents', sa.Column('current_generation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grandparents', 'current_generation', ['current_generation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grandparents', type_='foreignkey')
    op.drop_column('grandparents', 'current_generation_id')
    op.create_table('current__generation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'current__generation', ['name'], unique=False)
    op.create_index('name', 'current__generation', ['name'], unique=False)
    op.drop_table('parent_relation')
    op.drop_table('current_generation')
    # ### end Alembic commands ###
