"""empty message

Revision ID: 269a44bef5a8
Revises: 1279f9ee540b
Create Date: 2021-06-21 14:45:25.439567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '269a44bef5a8'
down_revision = '1279f9ee540b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parents_id', sa.Integer(), nullable=True),
    sa.Column('grand_parents_id', sa.Integer(), nullable=True),
    sa.Column('current_generation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_generation_id'], ['current_generation.id'], ),
    sa.ForeignKeyConstraint(['grand_parents_id'], ['grandparents.id'], ),
    sa.ForeignKeyConstraint(['parents_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parent_relation')
    op.drop_constraint('grandparents_ibfk_1', 'grandparents', type_='foreignkey')
    op.drop_constraint('grandparents_ibfk_2', 'grandparents', type_='foreignkey')
    op.drop_column('grandparents', 'parents_id')
    op.drop_column('grandparents', 'current_generation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grandparents', sa.Column('current_generation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grandparents', sa.Column('parents_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('grandparents_ibfk_2', 'grandparents', 'current_generation', ['current_generation_id'], ['id'])
    op.create_foreign_key('grandparents_ibfk_1', 'grandparents', 'parents', ['parents_id'], ['id'])
    op.create_table('parent_relation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parents_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grand_parents_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_generation_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_generation_id'], ['current_generation.id'], name='parent_relation_ibfk_1'),
    sa.ForeignKeyConstraint(['grand_parents_id'], ['grandparents.id'], name='parent_relation_ibfk_2'),
    sa.ForeignKeyConstraint(['parents_id'], ['parents.id'], name='parent_relation_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('parents_relation')
    # ### end Alembic commands ###
